[package]
name = "ms-learn-md-parser"
version = "0.0.1"
edition = "2021"

[lib]
name = "ms_doc_md_parser"
path = "src/lib.rs"

[dependencies]
deno_core = "0.175.0"
regex = "1.7.1"
scraper = "0.15.0"
serde = { version = "1.0.157", features = ["derive"] }
serde_yaml = "0.9.19"
